
###########################################################################
#              File     :    hcal_relval-layouts.py                       #
#              Purpose  :    Creates Hcal Layouts for data DQMs           #
#              Author   :    Shubham Pandey (shubham.pandey@cern.ch)      #
###########################################################################              

def hcalrechitDlayout(i, p, *rows): i[p] = DQMItem(layout=rows)

hcalrechitDlayout(dqmitems, 'DataLayouts/Hcal/RecHits/00 HE depth 3: occupancy vs ieta',[{'path' : 'HcalRecHitsD/HcalRecHitTask/occupancy_vs_ieta_HE3', 'draw' : { 'xmin' : '0.0', 'xmax' : '-1.0'}}])
hcalrechitDlayout(dqmitems, 'DataLayouts/Hcal/RecHits/01 HE depth 1: occupancy vs ieta',[{'path' : 'HcalRecHitsD/HcalRecHitTask/occupancy_vs_ieta_HE1', 'draw' : { 'xmin' : '0.0', 'xmax' : '-1.0'}}])
hcalrechitDlayout(dqmitems, 'DataLayouts/Hcal/RecHits/02 HE depth 2: occupancy vs ieta',[{'path' : 'HcalRecHitsD/HcalRecHitTask/occupancy_vs_ieta_HE2', 'draw' : { 'xmin' : '0.0', 'xmax' : '-1.0'}}])
hcalrechitDlayout(dqmitems, 'DataLayouts/Hcal/RecHits/03 severityLevel HB',[{'path' : 'HcalRecHitsD/HcalRecHitTask/HcalRecHitTask_severityLevel_HB', 'draw' : { 'xmin' : '0.0', 'xmax' : '25.0', 'ytype' : 'log'}}])
hcalrechitDlayout(dqmitems, 'DataLayouts/Hcal/RecHits/04 severityLevel HE',[{'path' : 'HcalRecHitsD/HcalRecHitTask/HcalRecHitTask_severityLevel_HE', 'draw' : { 'xmin' : '0.0', 'xmax' : '25.0', 'ytype' : 'log'}}])
hcalrechitDlayout(dqmitems, 'DataLayouts/Hcal/RecHits/05 severityLevel HF',[{'path' : 'HcalRecHitsD/HcalRecHitTask/HcalRecHitTask_severityLevel_HF', 'draw' : { 'xmin' : '0.0', 'xmax' : '25.0', 'ytype' : 'log'}}])
hcalrechitDlayout(dqmitems, 'DataLayouts/Hcal/RecHits/06 severityLevel HO',[{'path' : 'HcalRecHitsD/HcalRecHitTask/HcalRecHitTask_severityLevel_HO', 'draw' : { 'xmin' : '0.0', 'xmax' : '25.0', 'ytype' : 'log'}}])
hcalrechitDlayout(dqmitems, 'DataLayouts/Hcal/RecHits/07 HE status word',[{'path' : 'HcalRecHitsD/HcalRecHitTask/HcalRecHitTask_RecHit_StatusWord_HE', 'draw' : { 'xmin' : '0.0', 'xmax' : '-1.0', 'ytype' : 'log'}}])
hcalrechitDlayout(dqmitems, 'DataLayouts/Hcal/RecHits/08 HF status word',[{'path' : 'HcalRecHitsD/HcalRecHitTask/HcalRecHitTask_RecHit_StatusWord_HF', 'draw' : { 'xmin' : '0.0', 'xmax' : '-1.0', 'ytype' : 'log'}}])
hcalrechitDlayout(dqmitems, 'DataLayouts/Hcal/RecHits/09 HB status word',[{'path' : 'HcalRecHitsD/HcalRecHitTask/HcalRecHitTask_RecHit_StatusWord_HB', 'draw' : { 'xmin' : '0.0', 'xmax' : '-1.0', 'ytype' : 'log'}}])
hcalrechitDlayout(dqmitems, 'DataLayouts/Hcal/RecHits/10 HO status word',[{'path' : 'HcalRecHitsD/HcalRecHitTask/HcalRecHitTask_RecHit_StatusWord_HO', 'draw' : { 'xmin' : '0.0', 'xmax' : '-1.0'}}])
hcalrechitDlayout(dqmitems, 'DataLayouts/Hcal/RecHits/11 HO: occupancy vs ieta',[{'path' : 'HcalRecHitsD/HcalRecHitTask/occupancy_vs_ieta_HO', 'draw' : { 'xmin' : '0.0', 'xmax' : '-1.0'}}])
hcalrechitDlayout(dqmitems, 'DataLayouts/Hcal/RecHits/12 Mean energy vs ieta (GeV) HO ',[{'path' : 'HcalRecHitsD/HcalRecHitTask/emean_vs_ieta_HO', 'draw' : { 'xmin' : '0.0', 'xmax' : '-1.0'}}])
hcalrechitDlayout(dqmitems, 'DataLayouts/Hcal/RecHits/13 HO RecHits energy (GeV)',[{'path' : 'HcalRecHitsD/HcalRecHitTask/HcalRecHitTask_energy_of_rechits_HO', 'draw' : { 'xmin' : '0.0', 'xmax' : '60.0', 'ytype' : 'log'}}])
hcalrechitDlayout(dqmitems, 'DataLayouts/Hcal/RecHits/14 HB RecHits energy (GeV)',[{'path' : 'HcalRecHitsD/HcalRecHitTask/HcalRecHitTask_energy_of_rechits_HB', 'draw' : { 'xmin' : '0.0', 'xmax' : '600.0', 'ytype' : 'log'}}])
hcalrechitDlayout(dqmitems, 'DataLayouts/Hcal/RecHits/15 HE RecHits energy (GeV)',[{'path' : 'HcalRecHitsD/HcalRecHitTask/HcalRecHitTask_energy_of_rechits_HE', 'draw' : { 'xmin' : '0.0', 'xmax' : '-1.0', 'ytype' : 'log'}}])
hcalrechitDlayout(dqmitems, 'DataLayouts/Hcal/RecHits/16 HF RecHits energy (GeV)',[{'path' : 'HcalRecHitsD/HcalRecHitTask/HcalRecHitTask_energy_of_rechits_HF', 'draw' : { 'xmin' : '0.0', 'xmax' : '-1.0', 'ytype' : 'log'}}])
hcalrechitDlayout(dqmitems, 'DataLayouts/Hcal/RecHits/17 eta-phi RecHits Emap depth1',[{'path' : 'HcalRecHitsD/HcalRecHitTask/emap_depth1', 'draw' : { 'xmin' : '-42.0', 'xmax' : '42.0', 'ymin' : '0.0', 'ymax' : '72.0'}}])
hcalrechitDlayout(dqmitems, 'DataLayouts/Hcal/RecHits/18 eta-phi RecHits Emap depth2',[{'path' : 'HcalRecHitsD/HcalRecHitTask/emap_depth2', 'draw' : { 'xmin' : '-42.0', 'xmax' : '42.0', 'ymin' : '0.0', 'ymax' : '72.0'}}])
hcalrechitDlayout(dqmitems, 'DataLayouts/Hcal/RecHits/19 eta-phi RecHits Emap depth3',[{'path' : 'HcalRecHitsD/HcalRecHitTask/emap_depth3', 'draw' : { 'xmin' : '-42.0', 'xmax' : '42.0', 'ymin' : '0.0', 'ymax' : '72.0'}}])
hcalrechitDlayout(dqmitems, 'DataLayouts/Hcal/RecHits/20 eta-phi RecHits Emap depth4 ',[{'path' : 'HcalRecHitsD/HcalRecHitTask/emap_depth4', 'draw' : { 'xmin' : '-42.0', 'xmax' : '42.0', 'ymin' : '0.0', 'ymax' : '72.0'}}])
hcalrechitDlayout(dqmitems, 'DataLayouts/Hcal/RecHits/21 Mean energy vs ieta (GeV) HE depth1',[{'path' : 'HcalRecHitsD/HcalRecHitTask/emean_vs_ieta_HE1', 'draw' : { 'xmin' : '0.0', 'xmax' : '-1.0'}}])
hcalrechitDlayout(dqmitems, 'DataLayouts/Hcal/RecHits/22 Mean energy vs ieta (GeV) HE depth3',[{'path' : 'HcalRecHitsD/HcalRecHitTask/emean_vs_ieta_HE3', 'draw' : { 'xmin' : '0.0', 'xmax' : '-1.0'}}])
hcalrechitDlayout(dqmitems, 'DataLayouts/Hcal/RecHits/23 Mean energy vs ieta (GeV) HE depth2',[{'path' : 'HcalRecHitsD/HcalRecHitTask/emean_vs_ieta_HE2', 'draw' : { 'xmin' : '0.0', 'xmax' : '-1.0'}}])
hcalrechitDlayout(dqmitems, 'DataLayouts/Hcal/RecHits/24 Mean energy vs ieta (GeV) HF depth1',[{'path' : 'HcalRecHitsD/HcalRecHitTask/emean_vs_ieta_HF1', 'draw' : { 'xmin' : '0.0', 'xmax' : '-1.0'}}])
hcalrechitDlayout(dqmitems, 'DataLayouts/Hcal/RecHits/25 Mean energy vs ieta (GeV) HF depth2',[{'path' : 'HcalRecHitsD/HcalRecHitTask/emean_vs_ieta_HF2', 'draw' : { 'xmin' : '0.0', 'xmax' : '-1.0'}}])
hcalrechitDlayout(dqmitems, 'DataLayouts/Hcal/RecHits/26 Number of HO RecHits',[{'path' : 'HcalRecHitsD/HcalRecHitTask/N_HO', 'draw' : { 'xmin' : '0.0', 'xmax' : '600.0'}}])
hcalrechitDlayout(dqmitems, 'DataLayouts/Hcal/RecHits/27 Number of HF RecHits',[{'path' : 'HcalRecHitsD/HcalRecHitTask/N_HF', 'draw' : { 'xmin' : '0.0', 'xmax' : '2000.0'}}])
hcalrechitDlayout(dqmitems, 'DataLayouts/Hcal/RecHits/28 Number of HE RecHits',[{'path' : 'HcalRecHitsD/HcalRecHitTask/N_HE', 'draw' : { 'xmin' : '0.0', 'xmax' : '1200.0'}}])
hcalrechitDlayout(dqmitems, 'DataLayouts/Hcal/RecHits/29 Number of HB RecHits',[{'path' : 'HcalRecHitsD/HcalRecHitTask/N_HB', 'draw' : { 'xmin' : '0.0', 'xmax' : '1200.0'}}])
hcalrechitDlayout(dqmitems, 'DataLayouts/Hcal/RecHits/30 Mean energy vs ieta (GeV) HB depth1',[{'path' : 'HcalRecHitsD/HcalRecHitTask/emean_vs_ieta_HB1', 'draw' : { 'xmin' : '0.0', 'xmax' : '-1.0'}}])
hcalrechitDlayout(dqmitems, 'DataLayouts/Hcal/RecHits/31 Mean energy vs ieta (GeV) HB depth2',[{'path' : 'HcalRecHitsD/HcalRecHitTask/emean_vs_ieta_HB2', 'draw' : { 'xmin' : '0.0', 'xmax' : '-1.0'}}])
hcalrechitDlayout(dqmitems, 'DataLayouts/Hcal/RecHits/32 HB Aux status word',[{'path' : 'HcalRecHitsD/HcalRecHitTask/HcalRecHitTask_RecHit_Aux_StatusWord_HB', 'draw' : { 'xmin' : '0.0', 'xmax' : '-1.0', 'ytype' : 'log'}}])
hcalrechitDlayout(dqmitems, 'DataLayouts/Hcal/RecHits/33 HF Aux status word',[{'path' : 'HcalRecHitsD/HcalRecHitTask/HcalRecHitTask_RecHit_Aux_StatusWord_HF', 'draw' : { 'xmin' : '0.0', 'xmax' : '-1.0', 'ytype' : 'log'}}])
hcalrechitDlayout(dqmitems, 'DataLayouts/Hcal/RecHits/34 HE Aux status word',[{'path' : 'HcalRecHitsD/HcalRecHitTask/HcalRecHitTask_RecHit_Aux_StatusWord_HE', 'draw' : { 'xmin' : '0.0', 'xmax' : '-1.0', 'ytype' : 'log'}}])
hcalrechitDlayout(dqmitems, 'DataLayouts/Hcal/RecHits/35 HO Aux status word',[{'path' : 'HcalRecHitsD/HcalRecHitTask/HcalRecHitTask_RecHit_Aux_StatusWord_HO', 'draw' : { 'xmin' : '0.0', 'xmax' : '-1.0'}}])
hcalrechitDlayout(dqmitems, 'DataLayouts/Hcal/RecHits/36 HF depth 1: occupancy vs ieta',[{'path' : 'HcalRecHitsD/HcalRecHitTask/occupancy_vs_ieta_HF1', 'draw' : { 'xmin' : '0.0', 'xmax' : '-1.0'}}])
hcalrechitDlayout(dqmitems, 'DataLayouts/Hcal/RecHits/37 HF depth 2: occupancy vs ieta',[{'path' : 'HcalRecHitsD/HcalRecHitTask/occupancy_vs_ieta_HF2', 'draw' : { 'xmin' : '0.0', 'xmax' : '-1.0'}}])
hcalrechitDlayout(dqmitems, 'DataLayouts/Hcal/RecHits/38 HO Timing vs. Energy',[{'path' : 'HcalRecHitsD/HcalRecHitTask/HcalRecHitTask_timing_vs_energy_HO', 'draw' : { 'xmin' : '0.0', 'xmax' : '30.0'}}])
hcalrechitDlayout(dqmitems, 'DataLayouts/Hcal/RecHits/39 HB Timing vs. Energy',[{'path' : 'HcalRecHitsD/HcalRecHitTask/HcalRecHitTask_timing_vs_energy_HB', 'draw' : { 'xmin' : '0.0', 'xmax' : '500.0'}}])
hcalrechitDlayout(dqmitems, 'DataLayouts/Hcal/RecHits/40 HE Timing vs. Energy',[{'path' : 'HcalRecHitsD/HcalRecHitTask/HcalRecHitTask_timing_vs_energy_HE', 'draw' : { 'xmin' : '0.0', 'xmax' : '500.0'}}])
hcalrechitDlayout(dqmitems, 'DataLayouts/Hcal/RecHits/41 HF Timing vs. Energy',[{'path' : 'HcalRecHitsD/HcalRecHitTask/HcalRecHitTask_timing_vs_energy_HF', 'draw' : { 'xmin' : '0.0', 'xmax' : '-1.0'}}])
hcalrechitDlayout(dqmitems, 'DataLayouts/Hcal/RecHits/42 HB RecHits timing',[{'path' : 'HcalRecHitsD/HcalRecHitTask/HcalRecHitTask_timing_HB', 'draw' : { 'xmin' : '0.0', 'xmax' : '-1.0', 'ytype' : 'log'}}])
hcalrechitDlayout(dqmitems, 'DataLayouts/Hcal/RecHits/43 HE RecHits timing',[{'path' : 'HcalRecHitsD/HcalRecHitTask/HcalRecHitTask_timing_HE', 'draw' : { 'xmin' : '0.0', 'xmax' : '-1.0', 'ytype' : 'log'}}])
hcalrechitDlayout(dqmitems, 'DataLayouts/Hcal/RecHits/44 HF RecHits timing',[{'path' : 'HcalRecHitsD/HcalRecHitTask/HcalRecHitTask_timing_HF', 'draw' : { 'xmin' : '0.0', 'xmax' : '-1.0', 'ytype' : 'log'}}])
hcalrechitDlayout(dqmitems, 'DataLayouts/Hcal/RecHits/45 HO RecHits timing',[{'path' : 'HcalRecHitsD/HcalRecHitTask/HcalRecHitTask_timing_HO', 'draw' : { 'xmin' : '0.0', 'xmax' : '-1.0', 'ytype' : 'log'}}])
hcalrechitDlayout(dqmitems, 'DataLayouts/Hcal/RecHits/46 HB depth 2: occupancy vs ieta',[{'path' : 'HcalRecHitsD/HcalRecHitTask/occupancy_vs_ieta_HB2', 'draw' : { 'xmin' : '0.0', 'xmax' : '-1.0'}}])
hcalrechitDlayout(dqmitems, 'DataLayouts/Hcal/RecHits/47 HB depth 1: occupancy vs ieta',[{'path' : 'HcalRecHitsD/HcalRecHitTask/occupancy_vs_ieta_HB1', 'draw' : { 'xmin' : '0.0', 'xmax' : '-1.0'}}])
def calotowersDlayout(i, p, *rows): i[p] = DQMItem(layout=rows)

calotowersDlayout(dqmitems, 'DataLayouts/Hcal/CaloTowers/00 HE CaloTowers number',[{'path' : 'CaloTowersD/CaloTowersTask/CaloTowersTask_number_of_fired_towers_HE', 'draw' : { 'xmin' : '0.0', 'xmax' : '500.0'}}])
calotowersDlayout(dqmitems, 'DataLayouts/Hcal/CaloTowers/01 HF CaloTowers number',[{'path' : 'CaloTowersD/CaloTowersTask/CaloTowersTask_number_of_fired_towers_HF', 'draw' : { 'xmin' : '0.0', 'xmax' : '500.0'}}])
calotowersDlayout(dqmitems, 'DataLayouts/Hcal/CaloTowers/02 HB CaloTowers number',[{'path' : 'CaloTowersD/CaloTowersTask/CaloTowersTask_number_of_fired_towers_HB', 'draw' : { 'xmin' : '0.0', 'xmax' : '500.0'}}])
calotowersDlayout(dqmitems, 'DataLayouts/Hcal/CaloTowers/03 HF Calo MET (GeV)',[{'path' : 'CaloTowersD/CaloTowersTask/CaloTowersTask_MET_HF', 'draw' : { 'xmin' : '0.0', 'xmax' : '200.0', 'ytype' : 'log'}}])
calotowersDlayout(dqmitems, 'DataLayouts/Hcal/CaloTowers/04 HE Calo MET (GeV)',[{'path' : 'CaloTowersD/CaloTowersTask/CaloTowersTask_MET_HE', 'draw' : { 'xmin' : '0.0', 'xmax' : '700.0', 'ytype' : 'log'}}])
calotowersDlayout(dqmitems, 'DataLayouts/Hcal/CaloTowers/05 HB Calo MET (GeV)',[{'path' : 'CaloTowersD/CaloTowersTask/CaloTowersTask_MET_HB', 'draw' : { 'xmin' : '0.0', 'xmax' : '800.0', 'ytype' : 'log'}}])
calotowersDlayout(dqmitems, 'DataLayouts/Hcal/CaloTowers/06 problematic cells number HB',[{'path' : 'CaloTowersD/CaloTowersTask/number_of_problematic_cells_Hcal_HB', 'draw' : { 'xmin' : '0.0', 'xmax' : '5.0', 'ytype' : 'log'}}])
calotowersDlayout(dqmitems, 'DataLayouts/Hcal/CaloTowers/07 problematic cells number HF',[{'path' : 'CaloTowersD/CaloTowersTask/number_of_problematic_cells_Hcal_HF', 'draw' : { 'xmin' : '0.0', 'xmax' : '5.0', 'ytype' : 'log'}}])
calotowersDlayout(dqmitems, 'DataLayouts/Hcal/CaloTowers/08 problematic cells number HE',[{'path' : 'CaloTowersD/CaloTowersTask/number_of_problematic_cells_Hcal_HE', 'draw' : { 'xmin' : '0.0', 'xmax' : '5.0', 'ytype' : 'log'}}])
calotowersDlayout(dqmitems, 'DataLayouts/Hcal/CaloTowers/09 CaloTowers Occupancy vs. iEta',[{'path' : 'CaloTowersD/CaloTowersTask/CaloTowersTask_occupancy_vs_ieta', 'draw' : { 'xmin' : '0.0', 'xmax' : '-1.0'}}])
calotowersDlayout(dqmitems, 'DataLayouts/Hcal/CaloTowers/10 problematic cells number EE',[{'path' : 'CaloTowersD/CaloTowersTask/number_of_problematic_cells_Ecal_EE', 'draw' : { 'xmin' : '0.0', 'xmax' : '26.0', 'ytype' : 'log'}}])
calotowersDlayout(dqmitems, 'DataLayouts/Hcal/CaloTowers/11 recovered cells number HE',[{'path' : 'CaloTowersD/CaloTowersTask/number_of_recovered_cells_Hcal_HE', 'draw' : { 'xmin' : '0.0', 'xmax' : '5.0', 'ytype' : 'log'}}])
calotowersDlayout(dqmitems, 'DataLayouts/Hcal/CaloTowers/12 recovered cells number HF',[{'path' : 'CaloTowersD/CaloTowersTask/number_of_recovered_cells_Hcal_HF', 'draw' : { 'xmin' : '0.0', 'xmax' : '5.0', 'ytype' : 'log'}}])
calotowersDlayout(dqmitems, 'DataLayouts/Hcal/CaloTowers/13 recovered cells number HB',[{'path' : 'CaloTowersD/CaloTowersTask/number_of_recovered_cells_Hcal_HB', 'draw' : { 'xmin' : '0.0', 'xmax' : '5.0', 'ytype' : 'log'}}])
calotowersDlayout(dqmitems, 'DataLayouts/Hcal/CaloTowers/14 bad cells number HE',[{'path' : 'CaloTowersD/CaloTowersTask/number_of_bad_cells_Hcal_HE', 'draw' : { 'xmin' : '0.0', 'xmax' : '5.0', 'ytype' : 'log'}}])
calotowersDlayout(dqmitems, 'DataLayouts/Hcal/CaloTowers/15 bad cells number HF',[{'path' : 'CaloTowersD/CaloTowersTask/number_of_bad_cells_Hcal_HF', 'draw' : { 'xmin' : '0.0', 'xmax' : '5.0', 'ytype' : 'log'}}])
calotowersDlayout(dqmitems, 'DataLayouts/Hcal/CaloTowers/16 bad cells number HB',[{'path' : 'CaloTowersD/CaloTowersTask/number_of_bad_cells_Hcal_HB', 'draw' : { 'xmin' : '0.0', 'xmax' : '5.0', 'ytype' : 'log'}}])
calotowersDlayout(dqmitems, 'DataLayouts/Hcal/CaloTowers/17 HB CaloTowers EM Timing vs Energy',[{'path' : 'CaloTowersD/CaloTowersTask/CaloTowersTask_EM_Energy_Timing_HB', 'draw' : { 'xmin' : '0.0', 'xmax' : '800.0'}}])
calotowersDlayout(dqmitems, 'DataLayouts/Hcal/CaloTowers/18 HF CaloTowers EM Timing vs Energy',[{'path' : 'CaloTowersD/CaloTowersTask/CaloTowersTask_EM_Energy_Timing_HF', 'draw' : { 'xmin' : '0.0', 'xmax' : '-1.0'}}])
calotowersDlayout(dqmitems, 'DataLayouts/Hcal/CaloTowers/19 HE CaloTowers EM Timing vs Energy',[{'path' : 'CaloTowersD/CaloTowersTask/CaloTowersTask_EM_Energy_Timing_HE', 'draw' : { 'xmin' : '0.0', 'xmax' : '1500.0'}}])
calotowersDlayout(dqmitems, 'DataLayouts/Hcal/CaloTowers/20 HF CaloTowers HAD Timing vs Energy',[{'path' : 'CaloTowersD/CaloTowersTask/CaloTowersTask_HAD_Energy_Timing_HF', 'draw' : { 'xmin' : '0.0', 'xmax' : '-1.0'}}])
calotowersDlayout(dqmitems, 'DataLayouts/Hcal/CaloTowers/21 HE CaloTowers ECAL energy (GeV)',[{'path' : 'CaloTowersD/CaloTowersTask/CaloTowersTask_energy_ECAL_HE', 'draw' : { 'xmin' : '0.0', 'xmax' : '-1.0', 'ytype' : 'log'}}])
calotowersDlayout(dqmitems, 'DataLayouts/Hcal/CaloTowers/22 HF CaloTowers ECAL energy (GeV)',[{'path' : 'CaloTowersD/CaloTowersTask/CaloTowersTask_energy_ECAL_HF', 'draw' : { 'xmin' : '0.0', 'xmax' : '-1.0', 'ytype' : 'log'}}])
calotowersDlayout(dqmitems, 'DataLayouts/Hcal/CaloTowers/23 HB CaloTowers ECAL energy (GeV)',[{'path' : 'CaloTowersD/CaloTowersTask/CaloTowersTask_energy_ECAL_HB', 'draw' : { 'xmin' : '0.0', 'xmax' : '1500.0', 'ytype' : 'log'}}])
calotowersDlayout(dqmitems, 'DataLayouts/Hcal/CaloTowers/24 HB CaloTowers HCAL energy (GeV)',[{'path' : 'CaloTowersD/CaloTowersTask/CaloTowersTask_energy_HCAL_HB', 'draw' : { 'xmin' : '0.0', 'xmax' : '2000.0', 'ytype' : 'log'}}])
calotowersDlayout(dqmitems, 'DataLayouts/Hcal/CaloTowers/25 HE CaloTowers HCAL energy (GeV)',[{'path' : 'CaloTowersD/CaloTowersTask/CaloTowersTask_energy_HCAL_HE', 'draw' : { 'xmin' : '0.0', 'xmax' : '-1.0', 'ytype' : 'log'}}])
calotowersDlayout(dqmitems, 'DataLayouts/Hcal/CaloTowers/26 HF CaloTowers HCAL energy (GeV)',[{'path' : 'CaloTowersD/CaloTowersTask/CaloTowersTask_energy_HCAL_HF', 'draw' : { 'xmin' : '0.0', 'xmax' : '-1.0', 'ytype' : 'log'}}])
calotowersDlayout(dqmitems, 'DataLayouts/Hcal/CaloTowers/27 recovered cells number EB',[{'path' : 'CaloTowersD/CaloTowersTask/number_of_recovered_cells_Ecal_EB', 'draw' : { 'xmin' : '0.0', 'xmax' : '26.0', 'ytype' : 'log'}}])
calotowersDlayout(dqmitems, 'DataLayouts/Hcal/CaloTowers/28 problematic cells number EB',[{'path' : 'CaloTowersD/CaloTowersTask/number_of_problematic_cells_Ecal_EB', 'draw' : { 'xmin' : '0.0', 'xmax' : '26.0', 'ytype' : 'log'}}])
calotowersDlayout(dqmitems, 'DataLayouts/Hcal/CaloTowers/29 HF CaloTowers EM Timing',[{'path' : 'CaloTowersD/CaloTowersTask/CaloTowersTask_EM_Timing_HF', 'draw' : { 'xmin' : '0.0', 'xmax' : '-1.0', 'ytype' : 'log'}}])
calotowersDlayout(dqmitems, 'DataLayouts/Hcal/CaloTowers/30 HE CaloTowers EM Timing',[{'path' : 'CaloTowersD/CaloTowersTask/CaloTowersTask_EM_Timing_HE', 'draw' : { 'xmin' : '0.0', 'xmax' : '-1.0', 'ytype' : 'log'}}])
calotowersDlayout(dqmitems, 'DataLayouts/Hcal/CaloTowers/31 HB CaloTowers EM Timing',[{'path' : 'CaloTowersD/CaloTowersTask/CaloTowersTask_EM_Timing_HB', 'draw' : { 'xmin' : '0.0', 'xmax' : '-1.0', 'ytype' : 'log'}}])
calotowersDlayout(dqmitems, 'DataLayouts/Hcal/CaloTowers/32 HF CaloTowers HAD Timing',[{'path' : 'CaloTowersD/CaloTowersTask/CaloTowersTask_HAD_Timing_HF', 'draw' : { 'xmin' : '0.0', 'xmax' : '-1.0', 'ytype' : 'log'}}])
calotowersDlayout(dqmitems, 'DataLayouts/Hcal/CaloTowers/33 HE CaloTowers HAD Timing',[{'path' : 'CaloTowersD/CaloTowersTask/CaloTowersTask_HAD_Timing_HE', 'draw' : { 'xmin' : '0.0', 'xmax' : '-1.0', 'ytype' : 'log'}}])
calotowersDlayout(dqmitems, 'DataLayouts/Hcal/CaloTowers/34 HB CaloTowers HAD Timing',[{'path' : 'CaloTowersD/CaloTowersTask/CaloTowersTask_HAD_Timing_HB', 'draw' : { 'xmin' : '0.0', 'xmax' : '-1.0', 'ytype' : 'log'}}])
calotowersDlayout(dqmitems, 'DataLayouts/Hcal/CaloTowers/35 bad cells number EE',[{'path' : 'CaloTowersD/CaloTowersTask/number_of_bad_cells_Ecal_EE', 'draw' : { 'xmin' : '0.0', 'xmax' : '26.0', 'ytype' : 'log'}}])
calotowersDlayout(dqmitems, 'DataLayouts/Hcal/CaloTowers/36 bad cells number EB',[{'path' : 'CaloTowersD/CaloTowersTask/number_of_bad_cells_Ecal_EB', 'draw' : { 'xmin' : '0.0', 'xmax' : '26.0', 'ytype' : 'log'}}])
calotowersDlayout(dqmitems, 'DataLayouts/Hcal/CaloTowers/37 recovered cells number EE',[{'path' : 'CaloTowersD/CaloTowersTask/number_of_recovered_cells_Ecal_EE', 'draw' : { 'xmin' : '0.0', 'xmax' : '26.0', 'ytype' : 'log'}}])
calotowersDlayout(dqmitems, 'DataLayouts/Hcal/CaloTowers/38 Endcap CaloTowers SET (GeV)',[{'path' : 'CaloTowersD/CaloTowersTask/CaloTowersTask_SET_HE', 'draw' : { 'xmin' : '0.0', 'xmax' : '1000.0', 'ytype' : 'log'}}])
calotowersDlayout(dqmitems, 'DataLayouts/Hcal/CaloTowers/39 Forward CaloTowers SET (GeV)',[{'path' : 'CaloTowersD/CaloTowersTask/CaloTowersTask_SET_HF', 'draw' : { 'xmin' : '0.0', 'xmax' : '-1.0', 'ytype' : 'log'}}])
calotowersDlayout(dqmitems, 'DataLayouts/Hcal/CaloTowers/40 Barrel CaloTowers SET (GeV)	',[{'path' : 'CaloTowersD/CaloTowersTask/CaloTowersTask_SET_HB', 'draw' : { 'xmin' : '0.0', 'xmax' : '2200.0', 'ytype' : 'log'}}])
calotowersDlayout(dqmitems, 'DataLayouts/Hcal/CaloTowers/41 HE CaloTowers HAD Timing vs Energy',[{'path' : 'CaloTowersD/CaloTowersTask/CaloTowersTask_HAD_Energy_Timing_HE', 'draw' : { 'xmin' : '0.0', 'xmax' : '1500.0'}}])
calotowersDlayout(dqmitems, 'DataLayouts/Hcal/CaloTowers/42 HB CaloTowers HAD Timing vs Energy',[{'path' : 'CaloTowersD/CaloTowersTask/CaloTowersTask_HAD_Energy_Timing_HB', 'draw' : { 'xmin' : '0.0', 'xmax' : '600.0'}}])
def hcalnoiseratesDlayout(i, p, *rows): i[p] = DQMItem(layout=rows)

hcalnoiseratesDlayout(dqmitems, 'DataLayouts/Hcal/RBX/00 RBX energy type 3 (GeV)',[{'path' : 'HcalNoiseRatesD/HcalNoiseRatesTask/hRBXEnergyType3', 'draw' : { 'xmin' : '0.0', 'xmax' : '1200.0'}}])
hcalnoiseratesDlayout(dqmitems, 'DataLayouts/Hcal/RBX/01 RBX energy type 2 (GeV)',[{'path' : 'HcalNoiseRatesD/HcalNoiseRatesTask/hRBXEnergyType2', 'draw' : { 'xmin' : '0.0', 'xmax' : '1200.0'}}])
hcalnoiseratesDlayout(dqmitems, 'DataLayouts/Hcal/RBX/02 RBX energy type 1 (GeV)',[{'path' : 'HcalNoiseRatesD/HcalNoiseRatesTask/hRBXEnergyType1', 'draw' : { 'xmin' : '0.0', 'xmax' : '400.0'}}])
hcalnoiseratesDlayout(dqmitems, 'DataLayouts/Hcal/RBX/03 RBX number of hits',[{'path' : 'HcalNoiseRatesD/HcalNoiseRatesTask/hRBXNHits', 'draw' : { 'xmin' : '0.0', 'xmax' : '40.0'}}])
hcalnoiseratesDlayout(dqmitems, 'DataLayouts/Hcal/RBX/04 RBX energy (GeV)',[{'path' : 'HcalNoiseRatesD/HcalNoiseRatesTask/hRBXEnergy', 'draw' : { 'xmin' : '0.0', 'xmax' : '500.0'}}])




